use TCISystemQA

select	--O.OrgType, O.OrgName,
ISNULL(L1OG.OrgId,'')[CL1-ID],ISNULL(L1OG.OrgCode,'')[CL1-CODE],ISNULL(L1OG.OrgName,'')[CL1-NAME],ISNULL(L1OG.OrgType,'')[CL1-TYPE],
ISNULL(L2OG.OrgId,'')[CL2-ID],ISNULL(L2OG.OrgCode,'')[CL2-CODE],ISNULL(L2OG.OrgName,'')[CL2-NAME],ISNULL(L2OG.OrgType,'')[CL2-TYPE],
ISNULL(L3OG.OrgId,'')[CL3-ID],ISNULL(L3OG.OrgCode,'')[CL3-CODE],ISNULL(L3OG.OrgName,'')[CL3-NAME],ISNULL(L3OG.OrgType,'')[CL3-TYPE],
ISNULL(L4OG.OrgId,'')[CL4-ID],ISNULL(L4OG.OrgCode,'')[CL4-CODE],ISNULL(L4OG.OrgName,'')[CL4-NAME],ISNULL(L4OG.OrgType,'')[CL4-TYPE]
--ISNULL(L5OG.OrgId,'')[CL5-ID],ISNULL(L5OG.OrgCode,'')[CL5-CODE],ISNULL(L5OG.OrgName,'')[CL5-NAME],ISNULL(L5OG.OrgType,'')[CL5-TYPE]


FROM dbo.ORGS O WITH(NOLOCK)
JOIN dbo.OrgHierarchy OH WITH(NOLOCK)
ON O.OrgId=OH.OrgID
FULL JOIN dbo.OrgHierarchy L1 WITH(NOLOCK)
ON L1.hPATH.GetAncestor(1)=OH.hPATH
FULL JOIN ORGS L1OG WITH(NOLOCK)
ON L1.ORGID=L1OG.ORGID
FULL JOIN dbo.OrgHierarchy L2 WITH(NOLOCK)
ON L2.hPATH.GetAncestor(1)=L1.hPATH
FULL JOIN ORGS L2OG WITH(NOLOCK)
ON L2.ORGID=L2OG.ORGID

FULL JOIN dbo.OrgHierarchy L3 WITH(NOLOCK)
ON L3.hPATH.GetAncestor(1)=L2.hPATH
FULL JOIN ORGS L3OG WITH(NOLOCK)
ON L3.ORGID=L3OG.ORGID

FULL JOIN dbo.OrgHierarchy L4 WITH(NOLOCK)
ON L4.hPATH.GetAncestor(1)=L3.hPATH
FULL JOIN ORGS L4OG WITH(NOLOCK)
ON L4.ORGID=L4OG.ORGID

--FULL JOIN dbo.OrgHierarchy L5 WITH(NOLOCK)
--ON L5.hPATH.GetAncestor(1)=L4.hPATH
--FULL JOIN ORGS L5OG WITH(NOLOCK)
--ON L5.ORGID=L5OG.ORGID




WHERE O.OrgType='National'
AND ISNULL(L1OG.Terminated,'N')='N'
AND ISNULL(L2OG.Terminated,'N')='N'
AND ISNULL(L3OG.Terminated,'N')='N'
AND ISNULL(L4OG.Terminated,'N')='N'
--AND ISNULL(L5OG.Terminated,'N')='N'



--AND L1OG.OrgName LIKE 'Toyota Central'
--ORDER BY [CL6-TYPE],[CL5-TYPE],[CL4-TYPE],[CL3-TYPE],[CL2-TYPE],[CL1-TYPE]
ORDER BY [CL4-TYPE]



--select * from ORGS